name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Retrive project code
        uses: actions/checkout@v4

       
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: .src/Dockerfile
          tags: |
            adilsoncapitadev/fake-shop:latest
            adilsoncapitadev/fake-shop:v${{ github.run_number }}

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Authentication on AWS
        run: echo "Executing AWS configure command"

      - name: Configure kubectl
        run: echo "Executing aws eks update-kubeconfig command"

      - name: Apply manifest on Kubernetes
        run: echo "Executing kubectl apply"
